### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by Valarzz** [edu-rinaldi/NodeGit#1]
Hi, I build this project with `cmake .. -DND_BUILD_EXAMPLES=ON -DND_PARALLELIZE=ON`, then I try to run the `run_single_test.py` script:
`python ./script/diff_merge_test/run_single_test.py "./test/diff_merge/Shading/PaintedMetal/" "PaintedMetal" --is-shading`
It raised the error " No such file or directory: './bin/nd_blender'", then I changed the path to "--nd-exec "./examples/nd_blender", the whole script is:
`python ./script/diff_merge_test/run_single_test.py "./test/diff_merge/Shading/PaintedMetal/" "PaintedMetal" --is-shading --nd-exec "./examples/nd_blender"`
It raised the error "Permission denied: './examples/nd_blender'", I changed the permission with "chmod -R 777 ./examples/nd_blender" but it still can't work, do you have any ideas how I can solve this?

**Comment by edu-rinaldi** [comment]
@Valarzz I believe in this case it may be python not having the permissions to run some other executables. I suppose you're not on Windows, have you tried running `sudo python ...` ?

**Comment by edu-rinaldi** [comment]
Closing this for missing info.
